[tox]
envlist = py3
isolated_build = true

[testenv]
package = editable
extras = dev,bulma
commands =
    pytest -m "not splinter" -n auto {posargs}
    pytest -m splinter -n 0 --splinter-headless {posargs}
passenv =
    DISPLAY
    MOZ_HEADLESS
    GITHUB_*