# Generated by Django 6.0.6 on 2026-06-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage0Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stage0.stage0')),
            ],
        ),
    ]
