# Generated by Django 6.0.6 on 2026-06-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage0', '0002_stage0tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage0Tag',
        ),
    ]
