# Generated by Django 6.0.6 on 2026-06-23 09:47

from django.db import migrations
from django.contrib.auth.hashers import make_password


def test_users(apps, schema_editor):
    User = apps.get_model("djmvc_example", "User")
    User.objects.get_or_create(
        username="su",
        password=make_password("su"),
        is_superuser=True,
    )
    User.objects.get_or_create(
        username="staff",
        password=make_password("staff"),
        is_staff=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("djmvc_example", "0001_initial"),
    ]

    operations = [migrations.RunPython(test_users)]
