name: CI

on:
  push:
  pull_request:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install package and test dependencies
        run: |
          pip install -U pip
          pip install -U django
          pip install -e ".[dev,bulma]"

      - name: Run unit and integration tests
        run: pytest -m "not splinter"

      - name: Run browser tests
        run: pytest -m splinter -n 0 --splinter-headless

  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci
      - run: npm test